#!/bin/bash

DESKTOP_USER=che
HOME_DIRECTORIES="Downloads tmp"

for directory in $HOME_DIRECTORIES; do
    SIZE_BEFORE=$(du -hd0 /home/$DESKTOP_USER/$directory | awk -F' ' '{print $1}')
    echo "Size of directory \"/home/$DESKTOP_USER/$directory\" before cleanup is: $SIZE_BEFORE"
    find /home/$DESKTOP_USER/$directory/* -type f -mtime +30 -delete
    find /home/$DESKTOP_USER/$directory/* -type d -empty -delete
    SIZE_AFTER=$(du -hd0 /home/$DESKTOP_USER/$directory | awk -F' ' '{print $1}')
    echo "Size of directory \"/home/$DESKTOP_USER/$directory\" after cleanup is: $SIZE_AFTER"
done
