#!/bin/bash

DIR_SOURCE='/home/che/'
DIR_DESTINATION='/mnt/smb/backups/che-home/'

rsync \
    --times \
    --verbose \
    --compress \
    --hard-links \
    --partial \
    --progress \
    --mkpath \
    --recursive \
    --exclude '.cache/' \
    --exclude '.local/share' \
    --exclude '.cursor/' \
    --exclude '.dbus/' \
    --exclude '.docker/' \
    --exclude '.eclipse/' \
    --exclude '.rustup/' \
    --exclude 'Downloads/' \
    $DIR_SOURCE $DIR_DESTINATION
